export default [
  'GET_TOPICS',
  'GET_ALL_TOPICS',
  'CREATE_TOPIC',
  'UPDATE_TOPIC',
  'DELETE_TOPIC',
  'APPROVE_TOPIC',

  'GET_USERS',
  'CREATE_USER',
  'UPDATE_USER',
  'DELETE_USER',

  'GET_PROFILE',
  'UPDATE_PROFILE',
  'CHANGE_PASSWORD',

  'GET_CATEGORIES',
  'CREATE_CATEGORY',
  'UPDATE_CATEGORY',
  'DELETE_CATEGORY',
  'GET_ALL_CATEGORIES',

  'GET_SCHEDULES',
  'GET_SCHEDULE_DETAILS',
  'RATE_SCHEDULE',
  'AVG_RATE_SCHEDULE',
  'CREATE_SCHEDULE',
  'UPDATE_SCHEDULE',
  'JOIN_SCHEDULE',
  'GET_USERS_RATE',
  'DELETE_SCHEDULE'
]
